#!/usr/bin/env bash
# scripts/gen_adr_index.sh — auto-generate docs/decisions/README.md
#
# Walks docs/decisions/{proposed,accepted,deferred,deprecated,superseded}/
# and emits the canonical ADR index table. The committed README.md is
# compared against this script's output in CI; any drift fails the build.
#
# Idempotent: running twice produces identical output.
#
# Usage:
#   scripts/gen_adr_index.sh                # print to stdout
#   scripts/gen_adr_index.sh --update       # rewrite docs/decisions/README.md in place
#   scripts/gen_adr_index.sh --check       # exit 0 if README matches, 1 otherwise
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

DECISIONS_DIR="docs/decisions"
STATES=(proposed validated accepted deferred deprecated superseded)

emit_header() {
    echo "# Planex Architecture Decision Records"
    echo
    echo "> Auto-generated by \`scripts/gen_adr_index.sh\`. Do not edit by hand."
    echo "> Drift between this file and the script's output is a CI failure."
    echo "> See \`doc-organization.md\` Principle 8 (ADR-0001 is the implicit index)."
    echo
    echo "ADR lifecycle state is encoded in the directory:"
    echo "- \`accepted/\` — Active decisions that govern the codebase today."
    echo "- \`validated/\` — ADRs whose enforcement mechanism is implemented and proven to fire on a synthetic violation case (ADR-0014's TC39 Stage 2.7 analog). Cannot reach \`accepted/\` until the demonstration is in place."
    echo "- \`proposed/\` — Draft ADRs not yet ruled on."
    echo "- \`deferred/\`  — ADRs whose own acceptance is deferred (distinct from \`accepted/ADR-*\` that decide to defer something)."
    echo "- \`deprecated/\` — ADRs whose decision is no longer active and has no specific successor."
    echo "- \`superseded/\` — ADRs replaced by a named later ADR (bidirectional link in the ADR body)."
    echo
    echo "ADR numbering (ADR-0001 onward) is permanent; the directory only encodes the current lifecycle state, never the numbering."
    echo
    echo "ADR-0015 is permanently reserved by \`tests/synthetic_adr_0015.md\` — the deliberately bad synthetic ADR that \`check_essence_admission.sh --synthetic\` must reject (ADR-0014's falsifiability demonstration). The number is retired, not missing: no real ADR will ever carry it."
    echo
    echo "| # | Title | Status |"
    echo "|---|-------|--------|"
}

emit_row() {
    local file="$1"
    local state="$2"
    local num title
    num=$(basename "$file" | grep -oE 'ADR-[0-9]+' | sed 's/ADR-//')
    # Extract the first H1 line, strip the leading "# ADR-NNNN: " prefix.
    title=$(grep -m1 '^# ' "$file" | sed 's/^# //; s/^ADR-[0-9]*: //I')
    # If the title still starts with "ADR-NNNN", strip it.
    title=$(echo "$title" | sed -E "s/^ADR-[0-9]+:\s*//I")
    # Escape pipes in title (rare but possible).
    title="${title//|/\\|}"
    echo "| ADR-${num} | [${title}](${state}/$(basename "$file")) | ${state} |"
}

emit_body() {
    for state in "${STATES[@]}"; do
        local dir="$DECISIONS_DIR/$state"
        if [[ ! -d "$dir" ]]; then
            continue
        fi
        # Find ADR files in this dir, sorted numerically.
        for f in $(ls "$dir"/ADR-*.md 2>/dev/null | sort -t- -k2 -n); do
            [[ -f "$f" ]] || continue
            emit_row "$f" "$state"
        done
    done
}

emit_footer() {
    echo
    echo "## Templates and rules"
    echo
    echo "- [\`TEMPLATE.md\`](TEMPLATE.md) — the ADR template, including the mandatory \`## CAVEATS\` and \`## HISTORY\` sections (Principle 2 of \`doc-organization.md\`)."
    echo
    echo "## Companion documents"
    echo
    echo "- [\`doc-organization.md\`](../doc-organization.md) — the proposal that introduced lifecycle-as-directory (Principle 1) and the auto-generated index (Principle 8)."
    echo "- [\`abstraction-form.md\`](../concepts/canonical/abstraction-form.md) — Prerequisite 3 (falsifiability) that the ADR lifecycle and CAVEATS section distribute per-ADR."
    echo "- [\`leak-budgets.md\`](../concepts/canonical/leak-budgets.md) — quantitative L1/L2 audit that ADR-0013 first exercised as a retire cycle."
}

main() {
    local mode="${1:-print}"
    local output
    output=$(emit_header; emit_body; emit_footer)
    case "$mode" in
        --update)
            echo "$output" > "$DECISIONS_DIR/README.md"
            echo "updated $DECISIONS_DIR/README.md" >&2
            ;;
        --check)
            local committed
            committed=$(cat "$DECISIONS_DIR/README.md")
            if [[ "$output" == "$committed" ]]; then
                echo "OK: README.md matches gen_adr_index.sh output" >&2
                exit 0
            else
                echo "DRIFT: README.md does not match gen_adr_index.sh output" >&2
                echo "run: scripts/gen_adr_index.sh --update" >&2
                diff <(echo "$committed") <(echo "$output") | head -40
                exit 1
            fi
            ;;
        print|"")
            echo "$output"
            ;;
        *)
            echo "unknown mode: $mode" >&2
            echo "usage: $0 [--update|--check]" >&2
            exit 2
            ;;
    esac
}

main "$@"
